package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Act implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("act")
	private java.lang.Integer action = 1;
	private java.lang.Float prediction00;

	public Act() {
	}

	public java.lang.Integer getAction() {
		return this.action;
	}
	
	public java.lang.Float getPrediction00() {
		return this.prediction00;
	}

	public void setAction(java.lang.Integer action) {
		this.action = action;
	}
	
	public void setPrediction00(java.lang.Float prediction00) {
		this.prediction00 = prediction00;
	}

	public Act(java.lang.Integer action, java.lang.Float prediction00) {
		this.action = action;
		this.prediction00 = prediction00;
	}

}