package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Costfunc implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("costfunc")
	private java.lang.Float costoferror = 25.0f;
	private java.lang.Float costofchecking = 10.0f;

	public Costfunc() {
	}

	public java.lang.Float getCostoferror() {
		return this.costoferror;
	}
	
	public java.lang.Float getCostofchecking() {
		return this.costofchecking;
	}

	public void setCostoferror(java.lang.Float costoferror) {
		this.costoferror = costoferror;
	}
	
	public void setCostofchecking(java.lang.Float costofchecking) {
		this.costofchecking = costofchecking;
	}

	public Costfunc(java.lang.Float costoferror, java.lang.Float costofchecking) {
		this.costoferror = costoferror;
		this.costofchecking = costofchecking;
	}

}