package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dimension implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("dimension")
	private java.lang.Integer size = 3;

	public Dimension() {
	}

	public java.lang.Integer getSize() {
		return this.size;
	}

	public void setSize(java.lang.Integer size) {
		this.size = size;
	}

	public Dimension(java.lang.Integer size) {
		this.size = size;
	}

}