package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Products implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("products")
	private java.lang.String products = "['YYYY']";

	public Products() {
	}

	public java.lang.String getCannibals() {
		return this.products;
	}

	public void setCannibals(java.lang.String products) {
		this.products = products;
	}

	public Products(java.lang.String products) {
		this.products = products;
	}

}