package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("test")
	private java.lang.Integer preddraw = 1;
	private java.lang.Float predfrac = 0.9f;
	private java.lang.Float acc;
	private java.lang.Float tpr;
	private java.lang.Float tnr;
	private java.lang.Float ppv;
	private java.lang.Float npv;

	public Test() {
	}

	public java.lang.Integer getPreddraw() {
		return this.preddraw;
	}
	
	public java.lang.Float getPredfrac() {
		return this.predfrac;
	}
	
	public java.lang.Float getACC() {
		return this.acc;
	}
	
	public java.lang.Float getTPR() {
		return this.tpr;
	}
	
	public java.lang.Float getTNR() {
		return this.tnr;
	}
	
	public java.lang.Float getPPV() {
		return this.ppv;
	}
	
	public java.lang.Float getNPV() {
		return this.npv;
	}

	public void setPreddraw(java.lang.Integer preddraw) {
		this.preddraw = preddraw;
	}
	
	public void setPredfrac(java.lang.Float predfrac) {
		this.predfrac = predfrac;
	}
	
	public void setACC(java.lang.Float acc) {
		this.acc = acc;
	}
	
	public void setTPR(java.lang.Float tpr) {
		this.tpr = tpr;
	}
	
	public void setTNR(java.lang.Float tnr) {
		this.tnr = tnr;
	}
	
	public void setPPV(java.lang.Float ppv) {
		this.ppv = ppv;
	}
	
	public void setNPV(java.lang.Float npv) {
		this.npv = npv;
	}

	public Test(java.lang.Integer preddraw, java.lang.Float predfrac) {
		this.preddraw = preddraw;
		this.predfrac = predfrac;
		this.acc = acc;
		this.tpr = tpr;
		this.tnr = tnr;
		this.ppv = ppv;
		this.npv = npv;
	}

}