package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Train implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("train")
	private java.lang.Integer training = 1;
	private java.lang.Integer folds = 5;
	private java.lang.Float bagfrac = 0.99f;
	private java.lang.String weights = "";
	private java.lang.Integer weightsaccval = 1;
	private java.lang.Integer weightsacctst = 0;

	public Train() {
	}

	public java.lang.Integer getTraining() {
		return this.training;
	}

	public java.lang.Integer getFolds() {
		return this.folds;
	}

	public java.lang.Float getBagfrac() {
		return this.bagfrac;
	}
	
	public java.lang.String getWeights() {
		return this.weights;
	}
	
	public java.lang.Integer getWeightsaccval() {
		return this.weightsaccval;
	}
	
	public java.lang.Integer getWeightsacctst() {
		return this.weightsacctst;
	}

	public void setTraining(java.lang.Integer training) {
		this.training = training;
	}
	
	public void setFolds(java.lang.Integer folds) {
		this.folds = folds;
	}

	public void setBagfrac(java.lang.Float bagfrac) {
		this.bagfrac = bagfrac;
	}

	public void setWeights(java.lang.String weights) {
		this.weights = weights;
	}
	
	public void setWeightsaccval(java.lang.Integer weightsaccval) {
		this.weightsaccval = weightsaccval;
	}
	
	public void setWeightsacctst(java.lang.Integer weightsacctst) {
		this.weightsacctst = weightsacctst;
	}

	public Train(java.lang.Integer training, java.lang.Integer folds, java.lang.Float bagfrac, java.lang.String weights, java.lang.Integer weightsaccval, java.lang.Integer weightsacctst) {
		this.training = training;
		this.folds = folds;
		this.bagfrac = bagfrac;
		this.weights = weights;
		this.weightsaccval = weightsaccval;
		this.weightsacctst = weightsacctst;
	}

}