package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dropcols implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("dropcols")
	private java.lang.String droplist = "['id','gender','ever_married','work_type','residence_type','smoking_status','stroke']";

	public Dropcols() {
	}

	public java.lang.String getDroplist() {
		return this.droplist;
	}

	public void setDroplist(java.lang.String droplist) {
		this.droplist = droplist;
	}

	public Dropcols(java.lang.String droplist) {
		this.droplist = droplist;
	}

}