package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Iterations implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("iterations")
	private java.lang.Integer number = 1;

	public Iterations() {
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public Iterations(java.lang.Integer number) {
		this.number = number;
	}

}