package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Manage implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("manage")
	private java.lang.Integer publish = 1;

	public Manage() {
	}

	public java.lang.Integer getPublish() {
		return this.publish;
	}

	public void setPublish(java.lang.Integer publish) {
		this.publish= publish;
	}

	public Manage(java.lang.Integer publish) {
		this.publish = publish;
	}

}