package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Record implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("record")
	private java.math.BigInteger id;
	private java.lang.String gender;
	private java.lang.Integer age;
	private java.lang.Integer hypertension;
	private java.lang.Integer heart_disease;
	private java.lang.String ever_married;
	private java.lang.String work_type;
	private java.lang.String residence_type;
	private java.lang.Float avg_glucose_level;
	private java.lang.Float bmi;
	private java.lang.String smoking_status;
	private java.lang.Integer stroke;

	public Record() {
	}

	public java.math.BigInteger getId() {
		return this.id;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}
	
	public java.lang.Integer getHypertension() {
		return this.hypertension;
	}
	
	public java.lang.Integer getHeart_disease() {
		return this.heart_disease;
	}
	
	public java.lang.String getEver_married() {
		return this.ever_married;
	}

	public java.lang.String getWork_type() {
		return this.work_type;
	}

	public java.lang.String getResidence_type() {
		return this.residence_type;
	}

	public java.lang.Float getAvg_glucose_level() {
		return this.avg_glucose_level;
	}

	public java.lang.Float getBmi() {
		return this.bmi;
	}

	public java.lang.String getSmoking_status() {
		return this.smoking_status;
	}

	public java.lang.Integer getStroke() {
		return this.stroke;
	}

	public void setId(java.math.BigInteger id) {
		this.id = id;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public void setHypertension(java.lang.Integer hypertension) {
		this.hypertension = hypertension;
	}

	public void setHeart_disease(java.lang.Integer heart_disease) {
		this.heart_disease = heart_disease;
	}

	public void setEver_married(java.lang.String ever_married) {
		this.ever_married = ever_married;
	}

	public void setWork_type(java.lang.String work_type) {
		this.work_type = work_type;
	}

	public void setResidence_type(java.lang.String residence_type) {
		this.residence_type = residence_type;
	}

	public void setAvg_glucose_level(java.lang.Float avg_glucose_level) {
		this.avg_glucose_level = avg_glucose_level;
	}

	public void setBmi(java.lang.Float bmi) {
		this.bmi = bmi;
	}

	public void setSmoking_status(java.lang.String smoking_status) {
		this.smoking_status = smoking_status;
	}

	public void setStroke(java.lang.Integer stroke) {
		this.stroke = stroke;
	}

	public Record(java.math.BigInteger id, java.lang.String gender, java.lang.Integer age, java.lang.Integer hypertension, java.lang.Integer heart_disease, java.lang.String ever_married, java.lang.String work_type, java.lang.String residence_type, java.lang.Float avg_glucose_level, java.lang.Float bmi, java.lang.String smoking_status, java.lang.Integer stroke) {
		this.id = id;
		this.gender = gender;
		this.age = age;
		this.hypertension = hypertension;
		this.heart_disease = heart_disease;
		this.ever_married = ever_married;
		this.work_type = work_type;
		this.residence_type = residence_type;
		this.avg_glucose_level = avg_glucose_level;
		this.bmi = bmi;
		this.smoking_status = smoking_status;
		this.stroke = stroke;
	}

}