package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Samplestruct implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("samplestruct")
	private java.lang.Integer balancing = 1;

	public Samplestruct() {
	}

	public java.lang.Integer getBalancing() {
		return this.balancing;
	}

	public void setBalancing(java.lang.Integer balancing) {
		this.balancing = balancing;
	}

	public Samplestruct(java.lang.Integer balancing) {
		this.balancing = balancing;
	}

}