package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Validate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("validate")
	private java.lang.Integer testdraws = 1;

	public Validate() {
	}

	public java.lang.Integer getTestdraws() {
		return this.testdraws;
	}

	public void setTestdraws(java.lang.Integer testdraws) {
		this.testdraws = testdraws;
	}

	public Validate(java.lang.Integer testdraws) {
		this.testdraws = testdraws;
	}

}