package com.discovery.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Workdir implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("workdir")
	private java.lang.String path = "C:/xampp/htdocs/OpenEMR-7.0.2/interface/modules/custom_modules/oe-module-jbpm-generic-callout/public";

	public Workdir() {
	}

	public java.lang.String getPath() {
		return this.path;
	}

	public void setPath(java.lang.String path) {
		this.path = path;
	}

	public Workdir(java.lang.String path) {
		this.path = path;
	}

}